from pathlib import Path
from html import escape as e
import json,re
ROOT=Path(__file__).resolve().parents[1]
refs=json.loads((ROOT/'scripts/brand-reference.json').read_text(encoding='utf-8'))
old=(ROOT/'patriot-cleaning/index.html').read_text(encoding='utf-8')
bar=re.search(r'<div class="demo-browser"[\s\S]*?</label><a class="demo-browser__portfolio"[\s\S]*?</a></div>',old).group(0)
contacts={'patriot-cleaning':('208-989-5471','Patriotskyler@gmail.com'),'id-landscapes':('208-314-2675','208idlandscapes@gmail.com'),'blast-exterior-cleaning':('208-391-8145','derrick@blastcleanidaho.com'),'boise-home-painting':('208-724-9542','info@boisehomepainting.com'),'paintco':('','')}
def image(slug,i=0,alt='',cls='',lazy=True):
 return f'<img class="{cls}" src="../assets/brands/{slug}-{i}.webp" alt="{e(alt)}" loading="{"lazy" if lazy else "eager"}" decoding="async" width="1200" height="800">'
def head(kicker,title,copy='',cta='Explore services',target='services'):
 return f'<div class="intro"><span class="kicker">{kicker}</span><h1>{title}</h1><p>{copy}</p><a class="action" href="#{target}">{cta} <span>↗</span></a></div>'
def section(title,body,id='services',kicker='The details',cls=''):
 return f'<section id="{id}" class="section {cls}"><div class="section-title"><span class="kicker">{kicker}</span><h2>{title}</h2></div>{body}</section>'
def rows(items):
 return '<div class="service-rows">'+''.join(f'<article><span class="index">0{i+1}</span><h3>{t}</h3><p>{c}</p><a href="#contact" aria-label="Discuss {e(t)}">↗</a></article>' for i,(t,c) in enumerate(items))+'</div>'
def choices(items,label='Choose a service',kind='buttons'):
 return f'<div class="choice-tool" aria-label="{label}"><span class="kicker">{label}</span><div class="choice-buttons">'+''.join(f'<button type="button" data-choice="{e(desc)}" aria-pressed="{str(i==0).lower()}">{title}</button>' for i,(title,desc) in enumerate(items))+f'</div><p class="choice-result" role="status">{items[0][1]}</p></div>'
def checklist(items,title):
 return f'<div class="checklist"><h2>{title}</h2><p>Choose what you have in mind.</p>'+''.join(f'<label><input type="checkbox" value="{e(t)}"><span>{t}</span></label>' for t in items)+'<p class="check-summary" role="status">Your list is ready to start.</p><a class="action" href="#contact">Discuss this list ↗</a></div>'
def steps(items):
 return '<ol class="steps">'+''.join(f'<li><span>0{i+1}</span><div><h3>{a}</h3><p>{b}</p></div></li>' for i,(a,b) in enumerate(items))+'</ol>'
def faqs(items):
 return '<div class="faq">'+''.join(f'<details><summary>{t}<span>+</span></summary><p>{d}</p></details>' for t,d in items)+'</div>'
def contact(slug,title):
 b=refs[slug];phone,email=contacts.get(slug,(b.get('phone',''),b.get('email','')))
 details=(f'<a href="tel:+1{re.sub(chr(92)+"D","",phone)}">{e(phone)}</a>' if phone else '')+(f'<a href="mailto:{e(email)}">{e(email)}</a>' if email else '')
 return f'''<section id="contact" class="contact"><div><span class="kicker">Let’s talk about your project</span><h2>{title}</h2><div class="contact-links">{details}</div><a class="text-link" href="{b['original']}" target="_blank" rel="noopener">Visit the official business website ↗</a></div><form class="enquiry"><p class="form-note">Try the enquiry flow. This is a portfolio demo; nothing is sent.</p><label>Your name<input name="name" autocomplete="name" required></label><label>Email<input name="email" type="email" autocomplete="email" required></label><label>What do you have in mind?<textarea name="project" required rows="3"></textarea></label><button class="action" type="submit">Preview enquiry ↗</button><p class="form-result" role="status"></p></form></section>'''
def write(slug,body,title,nav=('Services','Approach'),contact_title='Tell us what you have in mind.'):
 b=refs[slug];name=b['brand'];html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(name)} | Independent redesign concept</title><meta name="description" content="{e(title)} — an independent website design study by River Hine."><link rel="icon" href="../assets/logo.svg"><link rel="stylesheet" href="../assets/bespoke.css?v=2"><link rel="stylesheet" href="../assets/browser.css?v=2"><script defer src="../assets/browser.js?v=2"></script><script defer src="../assets/bespoke.js?v=2"></script></head><body data-brand="{slug}">{bar}<div class="concept-label">Independent redesign concept by River Hine · Not the official business website</div><header class="business-header"><a class="wordmark" href="#top">{e(name)}</a><nav aria-label="Business concept"><a href="#services">{nav[0]}</a><a href="#approach">{nav[1]}</a><a class="nav-contact" href="#contact">Let’s talk ↗</a></nav></header><main id="top">{body}{contact(slug,contact_title)}</main><footer class="business-footer"><strong>{e(name)}</strong><p>Independent design study by River Hine. Business information and reference photography sourced from <a href="{b['original']}" target="_blank" rel="noopener">the official website</a>. Illustrations and interactive previews are conceptual. This demo is not affiliated with or endorsed by the business.</p><a href="../index.html">← Explore another demo</a></footer></body></html>''';(ROOT/slug/'index.html').write_text(html,encoding='utf-8')
# 01 / Patriot: an automotive service menu, red editorial typography and a cabin photograph.
s='patriot-cleaning'
body='<div class="patriot-hero">'+head('Meridian · Auto detailing','A fresh start.<br><em>Inside &amp; out.</em>','From the daily commute to the weekend drive. Explore detailing for the places your vehicle takes you.','Find your detail')+'<figure>'+image(s,0,'Vehicle interior shown on Patriot Cleaning’s website',lazy=False)+'<figcaption>Details make the difference.</figcaption></figure></div>'
body+=section('Your car. Your kind of clean.',choices([('Full detail','Interior and exterior care in one visit. Discuss your vehicle size and condition for a tailored quote.'),('Interior','Focus on the cabin: the seats, surfaces, and everyday spaces you use most.'),('Exterior','Focus on the finish, with exterior cleaning and waxing options.')],'Choose your detail')+'<div class="photo-pair">'+image(s,2,'Black truck exterior')+image(s,1,'Engine bay cleaning example')+'</div>',kicker='The detailing menu')
body+=section('Bring the car.<br>We’ll talk details.',steps([('Choose your focus','Inside, outside, or the whole vehicle.'),('Describe the vehicle','Tell the team about size, condition, and any areas that need attention.'),('Confirm your visit','Check current pricing and availability with Patriot Cleaning.')]),'approach','A simple start')
write(s,body,'A fresh start inside and out',contact_title='Ready for your next clean?')
# 02 / ID Landscapes: an immersive evening landscape spread.
s='id-landscapes'
body='<div class="night-hero">'+image(s,0,'Illuminated garden at night',lazy=False)+head('Landscape lighting · Meridian','The garden doesn’t<br>end at sunset.','Give paths, trees, and outdoor spaces a new life after dark.','Explore lighting')+'</div>'
body+=section('Light with a purpose.','<div class="lighting-grid">'+''.join('<article>'+image(s,i,alt)+f'<h3>{title}</h3><p>{copy}</p></article>' for i,alt,title,copy in [(2,'Path lighting','Find your way','Define paths and entrances with a considered lighting plan.'),(1,'Pool and tree lighting at night','Set the atmosphere','Bring depth and character to the places you enjoy outside.')])+'</div>',kicker='After dark')
body+=section('A little light.<br>A different feeling.','<div class="light-study">'+image(s,0,'Garden lighting mood study',cls='brightness-scene')+'<label>Explore the evening mood <input class="brightness" type="range" min="35" max="100" value="80" aria-label="Lighting preview brightness"></label><small>Visual mood study; not a product brightness specification.</small></div>'+rows([('Design','Begin with the paths, gathering spaces, and features you want to highlight.'),('Installation','Plan fixture placement and a lighting approach for the property.'),('Maintenance','Keep an existing lighting system looking its best.')]),'approach','A lighting study')
write(s,body,'Landscape lighting after sunset',('Lighting','The atmosphere'),'Let’s see your space in a new light.')
# 03 / Blast: high energy blue service dashboard, practical outdoor checklist.
s='blast-exterior-cleaning'
body='<div class="blast-hero">'+head('Treasure Valley · Exterior care','TAKE BACK<br>YOUR <em>OUTSIDE.</em>','Washing, lawn care, and property cleanup. Build a plan around what your outdoor space needs.','Build your cleanup')+'<div class="blast-art" aria-hidden="true"><span>FRESH<br>FROM THE<br>OUTSIDE IN.</span><i></i><b>BLAST / EXTERIOR CARE</b></div></div>'
body+=section('What needs attention?','<div class="blast-plan">'+checklist(['House or driveway wash','Lawn mowing','Leaves and yard debris','Junk and property cleanup'],'Build your outdoor list')+'<div><h3>One property.<br>More than one way to help.</h3><p>Choose a single service or describe a larger cleanup. The team can confirm the right scope for your property.</p>'+rows([('Washing','Pressure and soft washing options for home and business exteriors.'),('Lawn care','Traditional mowing and robotic mowing rental options.'),('Cleanup','Leaf removal, yard debris, and property clearing.')])+'</div></div>',kicker='Choose the work')
body+=section('From the curb<br>to the back fence.',steps([('Walk the property','Note the surfaces, lawn, and areas you want addressed.'),('Share the scope','Describe access, buildup, and the size of the job.'),('Get a quote','Confirm services and timing directly with Blast.')]),'approach','Your cleanup plan')
write(s,body,'Exterior care with a plan',('Cleanup list','How it works'),'A cleaner property starts here.')
# 04 / Boise Home Painting: a warm interior magazine with an interactive room.
s='boise-home-painting'
room='''<div class="paint-room" aria-label="Illustrated room color preview"><div class="room-window"></div><div class="room-picture"></div><div class="room-sofa"></div><div class="room-floor"></div><span>COLOR STUDY / ILLUSTRATION</span></div>'''
body='<div class="paint-editorial">'+head('Boise Home Painting','Make room<br>for <em>something new.</em>','Interior, exterior, and cabinet painting for homes and commercial spaces. A fresh finish can change how a place feels.','Explore the possibilities')+room+'</div>'
body+=section('Start with a feeling.','<div class="swatch-layout"><p>Try a few color directions in the illustrated room above. Then talk with the team about the real materials, light, and finish in your space.</p><div class="swatches" role="group" aria-label="Room color"><button data-color="#c5b9a5" style="--swatch:#c5b9a5" aria-pressed="true">Warm stone</button><button data-color="#819187" style="--swatch:#819187" aria-pressed="false">Quiet sage</button><button data-color="#657782" style="--swatch:#657782" aria-pressed="false">Blue hour</button><button data-color="#b8785f" style="--swatch:#b8785f" aria-pressed="false">Clay</button></div></div>'+rows([('Interiors','Walls, trim, and the rooms you spend your life in.'),('Exteriors','A fresh impression from the street.'),('Cabinets','A new direction for the heart of the home.'),('Commercial','Painting for workspaces and business interiors.')]),kicker='Explore color')
body+=section('The finish starts<br>before the paint.',steps([('Look at the space','Discuss the surfaces and the result you want.'),('Plan the preparation','Review repairs, protection, and finish choices.'),('Bring it together','Confirm the quote, schedule, and final details.')]),'approach','Considered from the start')
write(s,body,'An editorial approach to home painting',('Painting','The process'),'What would you like to refresh?')
# 05 / PAINTCO: bold poster graphics and a project-type planner.
s='paintco'
body='<div class="paintco-poster"><div class="poster-top"><span>BOISE / MERIDIAN / NAMPA</span><span>PAINT. TRANSFORM. REPEAT.</span></div>'+head('PAINTCO','BIG CHANGE.<br><em>FRESH COAT.</em>','A clear starting point for your next painting project.','Choose your project')+image(s,0,'House exterior from PAINTCO’s website',lazy=False)+'</div>'
body+=section('Where are we painting?',choices([('Inside','Start with the rooms, walls, and trim you want to update.'),('Outside','Tell the team about the exterior surfaces and their current condition.'),('Cabinets','Discuss your cabinet finish and the look you want to achieve.')],'Your project, first')+'<div class="paintco-stripe"><b>PREP.</b><b>PAINT.</b><b>ENJOY.</b></div>',kicker='Choose a direction')
body+=section('A new look.<br>A clear plan.','<div class="paintco-story">'+image(s,1,'Painted blue dining room')+'<div><h3>Good color deserves a good conversation.</h3><p>Bring your ideas, room photos, and questions. Confirm the work, materials, and schedule before the first coat.</p><a class="action" href="#contact">Start the conversation ↗</a></div></div>','approach','From idea to finish')
write(s,body,'A bold painting concept',('Projects','The plan'),'LET’S TALK PAINT.')
# 06 / Creative Surfaces: architectural portfolio, paired restoration photography.
s='creative-surfaces'
body='<div class="surface-cover"><div>'+head('Decorative concrete · Surface restoration','An ordinary surface.<br><em>Extraordinary potential.</em>','A study in texture, finish, and the details underfoot.','Explore the finishes')+'</div><div class="surface-images">'+image(s,0,'Concrete steps before resurfacing',lazy=False)+image(s,1,'Concrete steps after resurfacing',lazy=False)+'<span>Surface restoration · Images from the business website</span></div></div>'
body+=section('Made for the space.',choices([('Decorative','Explore a finish that adds character to an existing concrete surface.'),('Restoration','Discuss worn areas and what it would take to refresh the surface.'),('Industrial','Talk about the demands of the space and a suitable floor system.')],'Explore surface work')+'<div class="material-study" aria-label="Conceptual material palette"><span>01 / MINERAL</span><span>02 / TEXTURE</span><span>03 / FINISH</span></div>',kicker='Materials & possibilities')
body+=section('Look closer.',rows([('The existing surface','Condition and use shape the right approach.'),('The finish','Color and texture should suit the architecture.'),('The everyday demands','Discuss traffic, maintenance, and what the surface needs to withstand.')]),'approach','The project conversation')
write(s,body,'Concrete as an architectural material',('Surfaces','The details'),'What could your surface become?')
# 07 / Glidden: construction capability index, heavy civil photograph and field notebook.
s='glidden-concrete'
body='<div class="concrete-hero">'+head('Meridian, Idaho · Concrete construction','BUILT ON<br><em>SOLID GROUND.</em>','Architectural. Structural. Heavy civil. Flatwork. Find the right capability for the job.','View capabilities')+image(s,2,'Concrete construction equipment',lazy=False)+'<span class="drawing-label">PROJECT SCOPE / CONCRETE / IDAHO</span></div>'
body+=section('The capability index.',rows([('Architectural','Concrete work where the finish is part of the design.'),('Structural','A starting point for load-bearing project requirements.'),('Heavy civil','Discuss larger-scale infrastructure and site work.'),('Flatwork','Slabs, paths, and everyday working surfaces.')]),kicker='01 — Capabilities')
body+=section('Bring the scope.<br>Start the conversation.','<div class="scope-sheet"><h3>Project briefing</h3>'+choices([('Residential','Describe the property, access, and type of concrete work.'),('Commercial','Share the site requirements, plans, and intended use.'),('Civil','Discuss the project scope and supporting documents.')],'Select your project context')+'<p>Useful details: location · dimensions · access · drawings · preferred timing</p></div>','approach','02 — Planning')
write(s,body,'A construction capability showcase',('Capabilities','Project brief'),'LET’S DEFINE THE SCOPE.')
# 08 / Evenflo: calm comfort dashboard, clear temperature needs.
s='evenflo-heating'
body='<div class="comfort-hero">'+head('Evenflo Heating & Cooling','Back to<br><em>comfortable.</em>','Heating, cooling, and indoor air quality for your home. Start with what feels different.','Find your service')+'<div class="comfort-dial"><span>COMFORT STARTS HERE</span><div><b>72<span>°</span></b><small>ILLUSTRATIVE COMFORT SETTING</small></div><span>HEATING ↔ COOLING</span></div></div>'
body+=section('What’s happening at home?',choices([('Too warm','Explore cooling service. Describe when the problem started and which rooms are affected.'),('Too cold','Explore heating service. Share what the system is doing and the temperature changes you have noticed.'),('Uneven airflow','Discuss ductwork and indoor air quality with the team.'),('Time to replace','Talk through a system replacement or new-construction installation.')],'Choose your starting point'),kicker='A little clarity')
body+=section('The system behind<br>your everyday comfort.','<div class="hvac-grid">'+image(s,0,'Outdoor air conditioning units')+'<div>'+rows([('Repair','Describe the symptom and get the next step from a professional.'),('Install','Plan a system around the home and project.'),('Air quality','Consider airflow, ducts, and the indoor environment.')])+'</div></div>','approach','Heating · Cooling · Air quality')
write(s,body,'A comfort-first HVAC experience',('Find a service','Your system'),'Let’s get your home comfortable.')
# 09 / Meridian Tree: botanical print and tree-care field guide.
s='meridian-tree-service'
tree='''<div class="tree-print" aria-label="Illustrated tree canopy"><svg viewBox="0 0 500 540" role="img" aria-label="Tree illustration"><path d="M250 475V175M250 340L130 245M250 290L365 195M250 235L187 145" stroke="#e0d6b2" stroke-width="17" fill="none"/><g fill="#8aa176"><circle cx="140" cy="220" r="85"/><circle cx="342" cy="190" r="98"/><circle cx="215" cy="126" r="93"/><circle cx="285" cy="265" r="91"/></g><path d="M250 480V260M250 340L184 294M250 292L316 258" stroke="#ded8bb" stroke-width="10" fill="none"/></svg><span>CARE FOR WHAT GROWS HERE.</span></div>'''
body='<div class="tree-hero">'+tree+head('Meridian Tree Service · Family owned since 2003','A little care.<br><em>A stronger landscape.</em>','Tree and shrub care for Meridian and the surrounding Treasure Valley.','Open the field guide')+'</div>'
body+=section('What does your tree need?',faqs([('Trimming & pruning','Discuss growth, shape, and branches that need professional attention.'),('Tree & shrub removal','Ask the team to assess an unwanted or hazardous tree or shrub.'),('Stump grinding','Explore the next step after a tree has been removed.'),('Storm cleanup','Describe the damage and ask about cleanup. Keep clear of damaged limbs and power lines.')]),kicker='The tree-care field guide')
body+=section('Local roots.<br>Thoughtful care.','<div class="tree-story"><span class="year-stamp">EST.<b>2003</b></span><div><h3>Start with a walk around the property.</h3><p>Describe the tree, the surrounding space, and what concerns you. A free estimate is a chance to talk through the right approach.</p><p class="towns">Meridian · Boise · Eagle · Nampa · Kuna · Star</p></div></div>','approach','Know the space')
write(s,body,'A local tree-care field guide',('Tree care','Local roots'),'Tell us about your trees.')
# 10 / Garage: utilitarian repair-first landing, door selection.
s='garage-door-essentials'
body='<div class="garage-hero"><div>'+head('Garage Door Essentials · Eagle, Idaho','YOUR DAY<br>SHOULDN’T<br><em>STOP HERE.</em>','Repair, openers, and new doors. Find a clear starting point when your garage door needs attention.','Find your next step')+'</div><div class="garage-visual">'+image(s,0,'Wood-style garage doors',lazy=False)+'<span>REPAIR / REPLACE / MAINTAIN</span></div></div>'
body+=section('What brings you here?',choices([('Door won’t open','Contact the team about a repair. Describe the symptoms; leave spring and cable work to a professional.'),('Opener problem','Share the opener model and what happens when you use the remote or wall control.'),('A new door','Discuss the opening, style, and installation requirements.')],'Choose a starting point'),kicker='Get moving again')
body+=section('Function comes first.<br>Style comes with it.','<div class="door-gallery">'+image(s,1,'Garage door installation example')+'<div><h3>A door that suits the home.</h3><p>Explore replacement options after confirming size, operation, and the needs of the space.</p><a class="action" href="#contact">Discuss a new door ↗</a></div></div>','approach','Repair or replace')
write(s,body,'A repair-first garage door concept',('Get help','New doors'),'LET’S GET THE DOOR MOVING.')
# 11 / A1: a notebook task builder; no stock hero.
s='a1-handyman'
body='<div class="handyman-hero">'+head('A1 Handyman · Boise & Meridian','That list<br>isn’t getting<br><em>any shorter.</em>','Small repairs. Practical improvements. Start by getting everything in one place.','See what we can help with')+checklist(['Patch the drywall','Fix a sticking door','Repair cabinet hardware','Repair a fence or gate'],'Your home to-do list')+'</div>'
body+=section('A practical place to start.',rows([('Inside the home','Drywall, doors, cabinets, and everyday repairs.'),('Outside the home','Fences, decks, and siding repairs.'),('Install & improve','Fixtures, hardware, and useful household upgrades.')]),kicker='Room by room')
body+=section('Repair first.<br>Make it work again.','<div class="handyman-note"><span>THE A1 APPROACH</span><h3>Start with a list.<br>Finish with a plan.</h3><p>Bundle the jobs you have in mind. The team can review the scope, recommend an approach, and confirm what fits the service.</p><p>Licensed & insured · One-year written workmanship guarantee</p></div>','approach','Practical work, clearly explained')
write(s,body,'A task-first handyman experience',('The work','The approach'),'What’s on your list?')
# 12 / Peter: soft home-care catalog and room planner.
s='peters-carpet-cleaning'
body='<div class="carpet-hero">'+head('Peter’s Carpet Cleaning · Meridian','A fresh feeling.<br><em>Room to room.</em>','Carpet, furniture, and floor care for the spaces you live in.','Plan your clean')+'<div class="carpet-art" aria-label="Illustrated living room"><div class="soft-chair"></div><div class="soft-rug"></div><div class="soft-table"></div><span>MAKE YOURSELF AT HOME.</span></div></div>'
body+=section('Start with the surfaces.',choices([('Carpet','Discuss room count, traffic, and any spots or odors you want addressed.'),('Upholstery','Tell the team about the furniture and its fabric.'),('Tile & grout','Describe the surface and areas that need attention.'),('Hardwood','Talk through suitable cleaning for your flooring.')],'What needs a refresh?')+'<div class="room-planner"><label>Rooms to discuss <input type="number" min="1" max="30" value="2" aria-label="Number of rooms"></label><p role="status">2 rooms on your cleaning plan. Ask the team for a quote.</p></div>',kicker='Your cleaning plan')
body+=section('A local name.<br>A personal approach.','<div class="peter-letter"><span>A NOTE ABOUT THE SERVICE</span><h3>More than the carpet.</h3><p>Peter’s offers carpet, upholstery, tile and grout, and hardwood cleaning across the Treasure Valley. Share the areas that matter most to you and ask about the seven-step carpet process.</p><a class="text-link" href="#contact">Talk about your home ↗</a></div>','approach','Home is in the details')
write(s,body,'A room-by-room cleaning concept',('Plan your clean','The service'),'Let’s refresh your space.')
# 13 / Floor supply: large type, tactile material gallery, showroom appointment.
s='idaho-floor-supply'
body='<div class="floor-cover"><span class="kicker">Idaho Floor Supply / Garden City</span><h1>It all begins<br><em>underfoot.</em></h1><div class="floor-cover-grid">'+image(s,2,'Wood flooring detail',lazy=False)+'<div><p>Material, texture, and the way a room feels. Explore flooring with an installer-owned local showroom.</p><a class="action" href="#services">Find your material ↗</a><small>Showroom visits by appointment.</small></div></div></div>'
body+=section('A material conversation.','<div class="floor-materials"><article>'+image(s,2,'Hardwood surface')+'<h3>Wood character</h3><p>Grain, tone, and the warmth of a natural-looking finish.</p></article><article>'+image(s,1,'Carpet texture')+'<h3>Soft underfoot</h3><p>Texture and comfort for everyday spaces.</p></article><article>'+image(s,0,'Flooring installation')+'<h3>The installation</h3><p>Materials and installation belong in the same conversation.</p></article></div>'+choices([('Busy spaces','Discuss durability, cleaning, and the people or pets using the room.'),('Quiet rooms','Consider comfort, texture, and the atmosphere you want.'),('A whole project','Bring room dimensions and a sense of the overall direction.')],'What is the room like?'),kicker='Touch. Compare. Consider.')
body+=section('From sample<br>to everyday life.',steps([('Visit by appointment','See the materials and bring your room ideas.'),('Compare the details','Discuss use, feel, and installation needs.'),('Plan the floor','Confirm measurements, selections, and project scope.')]),'approach','The showroom journey')
write(s,body,'An editorial flooring showroom',('Materials','Visit the showroom'),'Find the floor that feels right.')
# 14 / J&A: landscape photo collage + project zoning.
s='ja-landscape'
body='<div class="landscape-cover">'+image(s,0,'Residential landscape from J and A’s website',lazy=False)+'<div>'+head('J & A Landscape · Nampa','A yard with<br><em>room for you.</em>','Shape the outdoor spaces around the way you want to use them.','Plan your outside')+'</div></div>'
body+=section('Make space for…','<div class="yard-grid">'+choices([('Gathering','Describe where you would like to sit, gather, and enjoy the yard.'),('A fresh start','Share what is not working in the current landscape.'),('Everyday upkeep','Discuss the ongoing care your property needs.')],'What matters in your yard?')+image(s,1,'Lawn and planted border')+'</div>',kicker='A landscape starts with living')
body+=section('Your space.<br>A shared direction.','<div class="landscape-path"><div><span>01 / LOOK</span><h3>Show the yard.</h3><p>Bring photos and a sense of how you use the space.</p></div><div><span>02 / PLAN</span><h3>Find the priorities.</h3><p>Talk through scope, layout, and upkeep.</p></div><div><span>03 / SHAPE</span><h3>Make it yours.</h3><p>Agree on the work and the next step.</p></div></div>','approach','From Nampa, for the Treasure Valley')
write(s,body,'A landscape made for everyday life',('Your yard','The plan'),'What could your yard become?')
# 15 / Boise Detail: motorsport-inspired illustrated profile and service selector.
s='boise-detail'
car='''<svg viewBox="0 0 900 350" role="img" aria-label="Illustrated car profile"><path d="M80 230l50-50 170-25 90-90h205l113 102 103 25 35 58H80Z" fill="#d9dedc"/><path d="M328 151l72-69h175l77 77Z" fill="#263634"/><path d="M465 85v70M105 220h708" stroke="#6b807b" stroke-width="7"/><circle cx="260" cy="242" r="57" fill="#101715"/><circle cx="260" cy="242" r="28" fill="#9ab4ab"/><circle cx="684" cy="242" r="57" fill="#101715"/><circle cx="684" cy="242" r="28" fill="#9ab4ab"/></svg>'''
body='<div class="detail-hero"><div class="detail-serial"><span>BOISE DETAIL</span><span>EST. 1991</span></div>'+head('Automotive care · Boise, Idaho','RESPECT<br><em>THE FINISH.</em>','Interior care, exterior restoration, and the details that make a vehicle feel like itself again.','Explore the treatment')+'<div class="car-profile">'+car+'<span>DESIGN STUDY / AUTOMOTIVE CARE</span></div></div>'
body+=section('Choose your focus.',choices([('The cabin','Focus on interior surfaces, upholstery, carpet, vinyl, and leather care.'),('The finish','Discuss exterior restoration and the condition of your paint.'),('The complete car','Talk about combining interior and exterior work for your vehicle.')],'Select a treatment direction')+'<div class="detail-spec"><span>01 / INTERIOR</span><span>02 / EXTERIOR</span><span>03 / THE DETAILS</span></div>',kicker='A considered treatment')
body+=section('Every vehicle<br>has a story.',rows([('Start with the condition','Describe the vehicle and the areas you want to improve.'),('Choose the focus','Compare interior and exterior service options.'),('Plan the visit','Confirm scope and availability with the Boise Detail team.')]),'approach','Care that starts with a conversation')
write(s,body,'A precision automotive design study',('Treatments','The approach'),'GIVE THE DETAILS SOME ATTENTION.')
print('Built 15 individually composed business demos')
